//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToyStore.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int Id { get; set; }
        public Nullable<int> Toys_FK { get; set; }
        public Nullable<int> Price_FK { get; set; }
        public Nullable<System.DateTime> DataOfSale { get; set; }
    
        public virtual Price Price { get; set; }
        public virtual Toy Toy { get; set; }
    }
}
