//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToyStore.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class StorrageOfToy
    {

       private ToyStoreContext _context = new ToyStoreContext();
        public int Id { get; set; }
        public Nullable<int> Toys_FK { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<System.DateTime> DateOfReceipt { get; set; }
        public Nullable<int> Soppliers_FK { get; set; }

        public virtual ToySopplier ToySopplier { get; set; }
        public virtual Toy Toy { get; set; }

        public  override string ToString()
        {
            Toy toy =  _context.Toys.FirstOrDefault(n => n.Id == Toys_FK);
            ToySopplier toySopplier = _context.ToySoppliers.FirstOrDefault(n => n.Id == Soppliers_FK);


            return $"{toy.NameOfToy}, Количество в партии:{Amount}, Поставщик:{toySopplier.SopplierName} ";
        }
    }
}
