//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToyStore.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Toy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Toy()
        {
            this.Prices = new HashSet<Price>();
            this.Sales = new HashSet<Sale>();
            this.StorrageOfToys = new HashSet<StorrageOfToy>();
        }
    
        public int Id { get; set; }
        public Nullable<decimal> ToyWeight { get; set; }
        public string NameOfToy { get; set; }
        public Nullable<int> Manufacturer_FK { get; set; }
        public Nullable<int> ToyTypes_FK { get; set; }
        public Nullable<int> CountryOfOrigin_FK { get; set; }
    
        public virtual CountryOfOrigin CountryOfOrigin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Price> Prices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StorrageOfToy> StorrageOfToys { get; set; }
        public virtual ToyManufacturer ToyManufacturer { get; set; }
        public virtual ToyType ToyType { get; set; }

        public override string ToString()
        {
            return $"{NameOfToy}";
        }
    }
}
