//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToyStore.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ToyStoreContext : DbContext
    {
        public ToyStoreContext()
            : base("name=ToyStoreContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CountryOfOrigin> CountryOfOrigins { get; set; }
        public virtual DbSet<Price> Prices { get; set; }
        public virtual DbSet<Sale> Sales { get; set; }
        public virtual DbSet<StorrageOfToy> StorrageOfToys { get; set; }
        public virtual DbSet<ToyManufacturer> ToyManufacturers { get; set; }
        public virtual DbSet<Toy> Toys { get; set; }
        public virtual DbSet<ToySopplier> ToySoppliers { get; set; }
        public virtual DbSet<ToyType> ToyTypes { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
