//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToyStore.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToyType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ToyType()
        {
            this.Toys = new HashSet<Toy>();
        }
    
        public int Id { get; set; }
        public string TypeOfToy { get; set; }
        public Nullable<int> AgeOfTargetMin { get; set; }
        public Nullable<int> AgeOfTargetMax { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Toy> Toys { get; set; }

        public override string ToString()
        {
            return $" {TypeOfToy}, возраст от {AgeOfTargetMin} до {AgeOfTargetMax}";
        }
    }
}
